
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8000/user


# jwt
forum: 
  jwt: 
    secret: rm!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!mD&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)Xv8HMH/72E,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb98FH^b[X3jzVER&:jw2<=c38=>L/zBq}C6tT*cCSVC^c]-L}&/
    expiration: 86400000